### ISSUE TITLE
Support for dry nutrients

### ISSUE THREAD

**Issue by 949mac** [ledgardener/gardenAutomation#1]
Great project!

I use a dry A+B+C mix for my grow. 

In fact, each plant stage has their own A+B+C mix. 

Any ideas to portion these out programmatically? I’m mainly interested in hardware ideas for this, as I’m sure I can figure out the programming. 

I typically portion anywhere from 5-12 grams per feeding (assuming the 5 gallon res is empty) if it matters. This is roughly 1 tea spoon to a heaping table spoon. 

Thanks again for this awesome project!

**Comment by 949mac** [comment]
☝️ Just a follow up. I think I'll try to mix my dry nutrients in a RO'd water solution. My biggest concern is shelf-life, but let's see how it works.

**Comment by ledgardener** [comment]
Hmmm, that's a tricky one, isn't it? Hopefully your "solution" works for you but I'll think the dry nutes over.
